---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-api
  template:
    metadata:
      labels:
        app: hpc-api
    spec:
      containers:
      - name: hpc-api
        image: hashicorp/http-echo:1.0.0
        args:
          - "-listen=:8080"