---
apiVersion: v1
kind: Namespace
metadata:
  name: weaponized-pod-02
---
apiVersion: v1
kind: Pod
metadata:
  namespace: weaponized-pod-02
  name: alpine
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: alpine
      image: alpine:latest
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        capabilities:
          drop:
            - ALL
      command:
        - /bin/sh
        - -c
        - --
      args:
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: log
          mountPath: /host/var/log
  volumes:
    - name: log
      hostPath:
        path: /var/log
