---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: gitops-example
 namespace: default
spec:
 interval: 60m
 url: https://github.com/chameleoncg/k8s-training-student-resources
 ref:
   branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: gitops-reconcile
 namespace: default
spec:
 interval: 10m
 targetNamespace: default
 sourceRef:
   kind: GitRepository
   name: gitops-example
 path: "./Day_3/Lesson_4_fluxcd/manifests"
 prune: true
 timeout: 1m